#!/usr/bin/env python
"""
 Copyright 2018 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 Permission is hereby granted, free of charge, to any person obtaining a copy of this
 software and associated documentation files (the "Software"), to deal in the Software
 without restriction, including without limitation the rights to use, copy, modify,
 merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
 permit persons to whom the Software is furnished to do so.
 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
 INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
 PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
 OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
 SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
"""

import time
import math
import rospy
from std_msgs.msg import Float64
from geometry_msgs.msg import Twist

class JetBotMotionControl:
    """ This class provides motion control and initializes the various motor controllers for the open source rover"""

    def __init__(self):
        rospy.loginfo("Motion control started...")

        self.robot_width = 45
        self.robot_length = 76
        self.max_turn_angle_in_radians = 0.78
        self.speed_scale_factor = 5
        self.constant_turn_angle_in_radians = 0.4

        self.controller_ns = "rover_ns"
        self.controller_command = "command"

        self.publishers = {
                "left_wheel_controller": None,
                "right_wheel_controller": None,
                "joint_state_controller": None
        }

        self.load_controllers()
        self.start()
        self.cmd_vel_msg = Twist()

        rospy.loginfo("Subscribing to command velocity (cmd_vel)...")
        rospy.Subscriber("/cmd_vel", Twist, self.cmd_vel_callback)

    def cmd_vel_callback(self, msg):
        self.cmd_vel_msg = msg

    # TODO: Add in checks to ensure controllers are loaded.
    def load_controllers(self):
        """ Initializes the controllers.  """
        rospy.loginfo("Loading controllers...")
        for controller in self.publishers:
            rospy.loginfo("Loading controller "+str(controller))
            topic = "/"+self.controller_ns+"/"+controller+"/"+self.controller_command
            self.publishers[controller] = rospy.Publisher(topic, Float64, queue_size=10)

    # Max value: 100, Min value: -100
    def send_motor_command(self, data):
        """ Send motor commands to each wheel motor controller."""
        rospy.loginfo("Received motor command: %s, %s", *data)
        v_l, v_r = data
        self.publishers['left_wheel_controller'].publish( v_l )
        self.publishers['right_wheel_controller'].publish( v_r )

    # Max rotation is 45 degrees.
    def send_steering_command(self, data):
        """ Send steering commands to the bogie and rocker. """
        rospy.loginfo(data)
        # TODO: determine a new way to steer

    # TODO: Implement backwards motion.
    def set_speed(self, speed):
        """ Set the current speed of the wheels. Max speed is 100, only go forwards. """

        # At this time, the robot only moves forward.
        if speed >= 0:
            self.send_motor_command([speed, speed])

    # TODO: Implement granular turing motions. Right now it is set to a constant.
    def set_turning_angle(self, angular_velocity):
        turn_angle_radians = 0.0
        if (angular_velocity<0):
            turn_angle_radians = self.constant_turn_angle_in_radians*-1
        elif (angular_velocity>0):
            turn_angle_radians = self.constant_turn_angle_in_radians

        self.send_steering_command([turn_angle_radians*-1,
         turn_angle_radians,
         turn_angle_radians*-1,
         turn_angle_radians])

    def start(self):
        """ Starting state of the robot. """
        self.set_turning_angle(0.0)
        self.set_speed(0.0)

    def move_with_cmd_vel(self):
        self.set_turning_angle(self.cmd_vel_msg.angular.z)
        self.set_speed(self.cmd_vel_msg.linear.x * self.speed_scale_factor)

if __name__ == "__main__":
    rospy.init_node("motion")
    rospy.loginfo("Starting the motion node...")
    jb_motion = JetBotMotionControl()
    rate = rospy.Rate(10.0)
    rospy.loginfo("Listening...")
    while not rospy.is_shutdown():
        jb_motion.move_with_cmd_vel()
        rate.sleep()


'''
# --------- Topic list ----------
# Wheels
/rover_ns/left_wheel_controller/command
/rover_ns/right_wheel_controller/command
'''
